# Generated by Django 5.0.6 on 2026-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(to='tracker.type', verbose_name='Типы'),
        ),
    ]
