# Generated by Django 5.2.15 on 2026-06-17 08:16

from django.db import migrations


def fill_project(apps, schema_editor):
    Project = apps.get_model('tracker', 'Project')
    Issue = apps.get_model('tracker', 'Issue')

    project = Project.objects.create(
        name='Тестовый проект',
        description='Создан миграцией',
        start_date='2026-01-01'
    )

    for issue in Issue.objects.all():
        issue.project = project
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_alter_issue_summary_issue_project'),
    ]

    operations = [
        migrations.RunPython(fill_project),
    ]