# Generated by Django 5.2.15 on 2026-06-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_project_owner'),
        ('tracker', '0008_groups'),
    ]

    operations = [
    ]
